### PR TITLE
go_get: support getting a/b/...

### LINKED ISSUE #278: go_get support for getting foo/bar/...
I was looking at updating a bunch of Go deps in //third_party/go for #277 - it would be useful to be able to specify:

    go_get(
        name = 'foo',
        get = 'github.com/foo/bar/...',
    )

to get a bunch of related packages in the same repo, but this doesn't currently seem to work, because the current rule tries to copy the '...' directory literally during the build.  You can't work around this by specifying your own `outs` either, because then the post-build scripts don't run to collect all the archives in pkg/.

### PR DESCRIPTION
**Pull request by tomlanyon**
Allows specifying paths ending in '...' as the 'get' parameter of go_get rules.

Fixes #278.

### CODE REVIEW

**Comment by tomlanyon** [comment]
I can't reproduce that CircleCI test failure on Darwin (and I can't see why it would fail); can I trigger CircleCI to re-run the test somehow?

**Comment by peterebden** [comment]
It looks suspiciously related, although weird it is not broken for Linux. I've retriggered a build, let's see how that goes.

**Comment by peterebden** [comment]
Ah, I guess this is go1.10 showing itself. The OSX build uses Brew to install things and is probably getting a new version of it (whereas the Linux one uses a Docker container that we've not updated yet).

We could pin it back temporarily, or just fix for 1.10 as in the other issue.

**Comment by peterebden** [comment]
OK, gonna merge this as is since I seem to be running into the same issue while attempting to fix #277 :)

**Pull request merged**
