### PR TITLE
Print build outputs without formatting when stdout is noninteractive

### LINKED ISSUE #2477: plz build to print outputs without formatting
A common pattern when writing scripts around please is to do `plz build x && plz query output x | ...`.  This seems overly verbose. Could an option be added to `plz build` (or make it the default behaviour) to print outputs to stdout in the same form as is done for `plz query outputs`. 
At the moment it looks like this:
```
$ plz build //vault/installer/images/crown_packages_image/build_crown_packages_image:vault_release_file 
Outputs:
//vault/installer/images/crown_packages_image/build_crown_packages_image:vault_release_file:
  plz-out/gen/vault/installer/images/crown_packages_image/build_crown_packages_image/vault-0.0.0.release
```
  
but it would be nice to have something like:
```
$ plz build //vault/installer/images/crown_packages_image/build_crown_packages_image:vault_release_file 
plz-out/gen/vault/installer/images/crown_packages_image/build_crown_packages_image/vault-0.0.0.release
```

### PR DESCRIPTION
**Pull request by peterebden**
Resolves #2477 

This is the most obvious way of doing it. Also thought about leaving off the flag and interleaving outputs to stdout/stderr but I think that might be confusing (although nice to not have yet another flag). Thoughts?

### CODE REVIEW

**Review by tiagovtristao — APPROVED** [review]
Ah nice, that's what I had in mind too when Toby reached out to me about this issue. :fast-pebers:

**Comment by peterebden** [comment]
OK updated a bit; this now autodetects based off whether stdout is a TTY, e.g.
```
$ plz plz build //src:please
Build finished; total time 1.17s, incrementality 100.0%. Outputs:
//src:please:
  plz-out/bin/src/please
$ plz plz build //src:please | head
plz-out/bin/src/please
```

**Review by samwestmoreland — APPROVED** [review]
Nice!

**Comment by tobyfielding1** [comment]
Gracias senor !

**Pull request merged**
