### PR TITLE
Set GOMAXPROCS at startup

### PR DESCRIPTION
**Pull request by peterebden**
We've had some good results from this internally. Would be interested to see what effect it has on our benchmark (where it should indeed set the limit quite differently to the default)

### CODE REVIEW

**Review by samwestmoreland — APPROVED** [review]
Nice! How did we set the procs before? Or did we not?

**Comment by peterebden** [comment]
We just followed the default Go behaviour (to honour the env var GOMAXPROCS and if not set it uses the number of current logical CPUs). This package is aware of cgroups on Linux so if running within a container will limit itself to the number of accessible CPUs rather than the total number - e.g. in our perf test, we should have 8 vCPUs available, but the machines generally appear to have 36 so we would likely overprovision OS threads.

**Comment by samwestmoreland** [comment]
Ah I see. Thanks!

**Review by tiagovtristao — APPROVED** [review]
Looking forward to seeing the results of this!

**Pull request merged**
