### PR TITLE
Fix bootstrap for Python 3.6

### LINKED ISSUE #177: bootstrap_pexer fails for python3
Using a pre-built `please` binary, building `//third_party/python:...` fails  because of what seems like an issue with the bootstrap_pexer. This also means the bootstrap script fails.

This is on ArchLinux. It looks like a python3-related issue; the `python` and `pip` binaries are aliases for `python3` and `pip3` but there is `python2` and `pip2` available, of course.

Adding `defaultinterpreter = python2` to the `.plzconfig` resolves the issue but is this the right fix?

Here's an excerpt, note the `python $(exe //tools/please_pex:bootstrap_pexer) --compile` . 
```
~/code/git/please $ plz build //third_party/python:... -v9
...
Error building target //third_party/python:_pkg_resources#zip: exit status 1
ENVIRONMENT:
PKG=third_party/python
ARCH=amd64
OS=linux
LANG=en_GB.UTF-8
PATH=/usr/local/bin:/usr/bin:/bin
TMP_DIR=/home/dim/code/git/please/plz-out/tmp/third_party/python/_pkg_resources#zip._build
SRCS=third_party/python/pkg_resources.py
OUTS=.pkg_resources.pex.zip
NAME=_pkg_resources#zip
TOOLS=/home/dim/code/git/please/plz-out/bin/tools/jarcat/jarcat /home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex python
OUT=/home/dim/code/git/please/plz-out/tmp/third_party/python/_pkg_resources#zip._build/.pkg_resources.pex.zip
SRC=third_party/python/pkg_resources.py
python $(exe //tools/please_pex:bootstrap_pexer) --compile && $(exe //tools/jarcat) -d -o ${OUTS} -i .
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/__main__.py", line 25, in <module>
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/.bootstrap/_pex/pex_bootstrapper.py", line 92, in bootstrap_pex
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/.bootstrap/_pex/finders.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/.bootstrap/pkg_resources.py", line 1518, in <module>
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
...
```

### PR DESCRIPTION
**Pull request by peterebden**
Basically just updating setuptools and pex, I don't have a machine convenient to test this on but the relevant code looks like it should be fixed.

Fixes #177 (hopefully)

### CODE REVIEW

**Comment by dimpavloff** [comment]
Thanks for looking into this on a Saturday! I tried the PR, the issue goes away 🎉 :)

I'm not sure if related or this is another issue but the bootstrap fails later on now, when running `//tools/jarcat`

```Error building target //tools/linter:_linter_test#pex: exit status 1
ENVIRONMENT:
PKG=tools/linter
ARCH=amd64
OS=linux
LANG=en_GB.UTF-8
PATH=/usr/local/bin:/usr/bin:/bin
TMP_DIR=/home/dim/code/git/please/plz-out/tmp/tools/linter/_linter_test#pex._build
SRCS=tools/linter/linter_test.py
OUTS=.linter_test_main.pex.zip
NAME=_linter_test#pex
TOOLS=/home/dim/code/git/please/plz-out/bin/tools/jarcat/jarcat /home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex python
OUT=/home/dim/code/git/please/plz-out/tmp/tools/linter/_linter_test#pex._build/.linter_test_main.pex.zip
SRC=tools/linter/linter_test.py
SRCS_SRCS=tools/linter/linter_test.py
python $(exe //tools/please_pex:bootstrap_pexer) --src_dir=${TMP_DIR} --out=temp.pex --entry_point=test_main --test_package=${PKG//\//.} --test_srcs=${SRCS_SRCS// /,} --interpreter=python --module_dir=third_party.python --zip_safe && $(exe //tools/jarcat) -i temp.pex -o $OUT --suffix=.pex --preamble="`head -n 1 temp.pex`"
15:51:35.511 CRITICAL: Error combining zip files: Error adding temp.pex to zipfile: zip: not a valid zip file
```

**Comment by peterebden** [comment]
That looks rather like it might be related to http://bugs.python.org/issue29094. I know 2.7.13 was broken for us, not sure if 3.6 is affected too but it seems plausible :(

I'm not sure what we can do if that is it, possibly detect & blacklist those particular versions?

**Comment by dimpavloff** [comment]
Oh, true! From that bug report 3.6 has been [patched](https://hg.python.org/cpython/rev/f36f9bce997d/) but it seems to be left for 3.6.1 https://docs.python.org/3.6/whatsnew/changelog.html

Thanks again!

**Comment by peterebden** [comment]
Agreed, I'm not sure what it is - looks sort of like it's using an old version of something, but debugging Travis is never great fun :( I'll try to force a rerun and see what happens.

**Comment by peterebden** [comment]
Got it, it was a real bug whereby we were importing pkg_resources from the system instead of in the pex (or at least had a mix of the two or something). I've also managed to cut some duplication out so the tool is smaller again.

**Comment by dimpavloff** [comment]
\o/

**Pull request merged**
