### PR TITLE
Depend on protoc to include wkt when it looks like a label

### PR DESCRIPTION
**Pull request by Tatskaari**
Fixes: #1641

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I was wondering if it would make sense to make the WKT rule a configurable rule in Please?

Or we could just get rid of that entirely? `proto_libraries` relying on WKT could add a dependency without relying on some automatic magic behind the scenes.

**Comment by Tatskaari** [comment]
> I was wondering if it would make sense to make the WKT rule a configurable rule in Please?
> 
> Or we could just get rid of that entirely? `proto_libraries` relying on WKT could add a dependency without relying on some automatic magic behind the scenes.

I think it's reasonable to assume that well known types will be handled automatically. A standard protoc install would put them under `/usr/local/include/google/protobuf`. Ideally `protoc_binary()` would behave similarly.

**Comment by sagikazarmark** [comment]
Would it make sense then to make it a separate rule and configuration? (eg. for whatever reason I want to use a custom version).

**Comment by Tatskaari** [comment]
> Would it make sense then to make it a separate rule and configuration? (eg. for whatever reason I want to use a custom version).

Seems pretty niche. You could write your own rule that outputs `protoc` and provides the well known types so it's possible if that became a use case.

**Review by peterebden — APPROVED** [review]

**Pull request merged**
