### PR TITLE
Change format of output so we can associate each file with a target.

### PR DESCRIPTION
**Pull request by peterebden**

### CODE REVIEW

**Comment by csdigi** [comment]
Not a listed reviewer but YOLO, LGTM.

**Comment by dimpavloff** [comment]
Obviously this will print a bit more than currently. Would this be annoying when using plz via the CLI?

**Comment by peterebden** [comment]
Only a little. I thought I might suppress the target name when you only build one, but could also control it by a flag. Thoughts?

**Comment by dimpavloff** [comment]
If only a little, then great, +1

Re suppressing the only target, I think that while it makes it friendlier it will be inconsistent compared to when building multiple targets which might be confusing. A flag feels like an overkill

**Comment by peterebden** [comment]
Okay thanks, I will leave it as is for now, we can easily revisit if it's a problem.

**Pull request merged**
