### PR TITLE
Make subinclude take annotated label and list

### LINKED ISSUE #2939: Subinclude error when target have a named output
I think `canonicalise` and `decompose` do not correctly handle some rules.

Example with subinclude
```
plz-out/gen/tools/pleasings/tools/golang/1.21.3_linux_arm64.subrepo.build_defs:1:1: error: Invalid build label: /////tools/pleasings/tools/golang:1.21.3_linux_arm64|golang_defs

subinclude('/////tools/pleasings/tools/golang:1.21.3_linux_arm64|golang_defs')
```

Also using canonicalise and decompose with a `@` prefix doesn't always work

### PR DESCRIPTION
**Pull request by izissise**
This adds the possibility to subinclude a target named output 

Fix #2939

### CODE REVIEW

**Comment by izissise** [comment]
I guess it was just an intermittent bug, relaunching the CI worked

**Comment by izissise** [comment]
@peterebden Hello, is it something please team doesn't want?

**Comment by Tatskaari** [comment]
> @peterebden Hello, is it something please team doesn't want?

No, sorry, definitely desirable to support annotated labels here. The team is just under a lot of pressure right now, and I think this slipped under our radar as I wasn't working over Christmas.

**Review by Tatskaari — APPROVED** [review]
Much appreciated! Looks good to me. :)

**Pull request merged**
