### PR TITLE
from plz rebuild to plz build --rebuild

### PR DESCRIPTION
**Pull request by SebastianoF**
Attempt to address the issue #523

### CODE REVIEW

**Comment by peterebden** [comment]
Thanks, looks good! Will keep this open until we're sure we're committed to v14 though since it's a breaking change.

**Comment by peterebden** [comment]
Hey, the time has come for this one, sorry it took a while. Can you resolve the merge conflicts please?

**Comment by SebastianoF** [comment]
It **should** work... !

**Comment by peterebden** [comment]
Thanks Sebastiano!

**Pull request merged**
