### PR TITLE
Remove call to `config.PrintAliases` if `--help` flag passed

### PR DESCRIPTION
**Pull request by samwestmoreland**
https://github.com/thought-machine/please-issues/issues/47

### CODE REVIEW

**Comment by samwestmoreland** [comment]
Ah this is still incorrect. Now it's printing `Help Options` twice.

**Review by Tatskaari — APPROVED** [review]
Looks good to me :)

**Comment by Tatskaari** [comment]
I guess this one can be closed?

**Comment by samwestmoreland** [comment]
Thanks!

**Pull request merged**
