### PR TITLE
Panic when srcs have spaces

### PR DESCRIPTION
**Pull request by Tatskaari**
Fixes: #1215

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Doesn't this make quoting paths in build rules entirely useless? Chances are source files and output directories are in the same file tree.

I'm not arguing against this as a solution, but life would be easier if quoting was dropped everywhere and spaces in paths declared as unsupported. It's not even a best-effort thing because of the above reason.

Am I missing something?

**Comment by Tatskaari** [comment]
> Doesn't this make quoting paths in build rules entirely useless? Chances are source files and output directories are in the same file tree.
> 
> I'm not arguing against this as a solution, but life would be easier if quoting was dropped everywhere and spaces in paths declared as unsupported. It's not even a best-effort thing because of the above reason.
> 
> Am I missing something?

Agreed. It needs more thought. Like perhaps we can do some sort of command replacement rather than using env variables.

**Comment by sagikazarmark** [comment]
Bump

**Comment by sagikazarmark** [comment]
Bump

**Pull request closed without merging**
