### PR TITLE
Remove hacky _CREATE_OUTPUT_DIRS thing

### PR DESCRIPTION
**Pull request by peterebden**
Since #1024 we shouldn't need this any more (thank goodness)

### CODE REVIEW

**Comment by Tatskaari** [comment]
Are we sure? I think there are other rules in core3 that do this (go_mocks). If we want to remove this hack we probably need to remove the add_out built in so its not possible to add outputs from a post build function.

**Comment by peterebden** [comment]
it's a little more subtle than that - it's not needed in general for adding outputs, only for build rules that fail when the output directory exists on re-execution.

**Comment by peterebden** [comment]
FWIW have tested some go_mock targets and they still build fine after this change.

**Comment by Tatskaari** [comment]
Okay I guess it would be better to have the rules accommodate this (i.e. by using || rather than && or something) rather than please itself.

**Pull request merged**
